states = {
    '1': 'Connecticut',
    '2': 'Maine',
    '3': 'Massachusetts',
    '4': 'New Hampshire',
    '5': 'Rhode Island',
    '6': 'Vermont',
    '11': 'Delaware',
    '12': 'New Jersey',  
    '13': 'New York',
    '14': 'Pennsylvania',
    '21': 'Illinois',
    '22': 'Indiana',
    '23': 'Michigan',   
    '24': 'Ohio',
    '25': 'Wisconsin',  
    '31': 'Iowa',
    '32': 'Kansas',
    '33': 'Minnesota',  
    '34': 'Missouri',
    '35': 'Nebraska',
    '36': 'North Dakota',
    '37': 'South Dakota',
    '40': 'Virginia',
    '41': 'Alabama',
    '42': 'Arkansas',
    '43': 'Florida',
    '44': 'Georgia',
    '45': 'Louisiana',
    '46': 'Mississippi',
    '47': 'North Carolina',
    '48': 'South Carolina',
    '49': 'Texas',
    '51': 'Kentucky',
    '52': 'Maryland',
    '53': 'Oklahoma',
    '54': 'Tennessee',
    '56': 'West Virginia',
    '61': 'Arizona',
    '62': 'Colorado',
    '63': 'Idaho',
    '64': 'Montana',
    '65': 'Nevada',
    '66': 'New Mexico',
    '67': 'Utah',
    '68': 'Wyoming',
    '71': 'California',
    '72': 'Oregon',
    '73': 'Washington',
    '81': 'Alaska',
    '82': 'Hawaii',
    '98': 'District of Columbia',
}
